# Document:
# http://simiki.org/docs/configuration.html

url: http://www.xu81.com/pubg_wiki/
title: 绝地求生中文维基
root: /pubg_wiki
keywords: 绝地求生,中文,维基百科
description: 绝地求生中文维基百科
author: viperasi

theme: simple2

category:
  - name: game
    label: 游戏
  - name: 武器
    label: 武器
  - name: equipment
    label: 装备
  - name: item
    label: 道具
  - name: vehicle
    label: 载具
  - name: myth
    label: 流言

pygments: true